# Generated by Django 5.0.8 on 2025-06-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartinput', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.IntegerField(),
        ),
    ]
