# Generated by Django 5.0.8 on 2025-06-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartinput', '0002_alter_year_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='name',
            new_name='year',
        ),
    ]
